# Generated by Django 4.1.4 on 2022-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUc', models.CharField(max_length=100)),
                ('nomCapteur', models.CharField(max_length=100)),
                ('valeurCapteur', models.FloatField()),
            ],
        ),
    ]
