# Generated by Django 4.1.2 on 2023-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetrie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='nomUc',
            new_name='Employe1',
        ),
        migrations.AlterField(
            model_name='data',
            name='valeurCapteur',
            field=models.CharField(max_length=100),
        ),
    ]
