# Generated by Django 4.1.2 on 2023-01-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetrie', '0002_rename_nomuc_data_employe1_alter_data_valeurcapteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Employe1',
            new_name='Employe',
        ),
    ]
