# Generated by Django 4.1.2 on 2023-01-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telemetrie', '0003_rename_employe1_data_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='nomCapteur',
        ),
        migrations.RemoveField(
            model_name='data',
            name='valeurCapteur',
        ),
    ]
